name: CI/CD release - DirtyCouture

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      #Optional: tests already running in main
      - name: Run tests
        run: ./gradlew test
            
	    - name: Trigger Render Deploy Hook
	      env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK}}
		      DB_URL: ${{secrets.DATABASE_URL }}
		      DB_USER: ${{ secrets.DB_USER }}
		      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
	      run: |
		      curl -X POST "$RENDER_DEPLOY_HOOK"

