name: Kotlin CI - DirtyCouture

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
        uses: actions/checkout@v4

    - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

    - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

    - name: Build with Gradle
        run: ./gradlew build

    - name: Run tests
        run: ./gradlew test
